# Pre-merge checks

# This workflow is triggered on pull requests to main and release branches and
# - scans GitHub Actions workflows for security issues (Zizmor)
# - analyzes Python code security in changed files (Bandit)

name: "Pre-merge checks"

on:
  pull_request:
    branches:
      - main
      - releases/**

permissions: {} # No permissions by default

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  zizmor-scan-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          # FIXME: needed for tj-actions/changed-files to gather changed files, once repository becomes public this argument should be set to false
          persist-credentials: true
      - name: Run Zizmor scan
        uses: open-edge-platform/geti-ci/actions/zizmor@eac3c48b3404ab21827cf2fbbeab8669fb282d52
        with:
          scan-scope: "changed"
          severity-level: "LOW"
          confidence-level: "LOW"
          fail-on-findings: true
          output-format: "plain" # Use plain text output format to omit uploading code scanning results to Security tab

  bandit-scan-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          # FIXME: needed for tj-actions/changed-files to gather changed files, once repository becomes public this argument should be set to false
          persist-credentials: true
      - name: Run Bandit scan
        uses: open-edge-platform/geti-ci/actions/bandit@eac3c48b3404ab21827cf2fbbeab8669fb282d52
        with:
          scan-scope: "changed"
          severity-level: "LOW"
          confidence-level: "LOW"
          fail-on-findings: true
          output-format: "txt" # Use plain text output format to omit uploading code scanning results to Security tab
